### ISSUE TITLE
Grid wrapper class

### ISSUE THREAD

**Issue by freiden** [rafaelfranca/simple_form-bootstrap#63]
Hi,
I'm trying to use an `horizontal_form` for a simple input with a label and I'm trying to change the size of the input by using bootstrap class but it doesn't work. By looking in details the code the `grid_wrapper` has the following class `col-sm-9` and despite the fact that I try to use `grid_wrapper_html` to specify a bootstrap class the initial is still present.

Is there any way of replace this value with my own without creating a custom wrapper?

Thanks in advance.

**Comment by m5o** [comment]
It is also possible to pass any html attribute straight to the input, by using the `:input_html` option, for instance:

```erb
<%= f.input :name, input_html: { class: "form-control-lg" } %>
```

##### Preview
![screen shot 2018-08-23 at 12 56 56](https://user-images.githubusercontent.com/26371/44521641-0dd2da80-a6d4-11e8-9cfe-a24f71540b6a.png)

📝 https://github.com/plataformatec/simple_form#usage
🎨 https://getbootstrap.com/docs/4.1/components/forms/#sizing
