### ISSUE TITLE
setup depfu to keep dependencies up-to-date

### ISSUE THREAD

**Issue by m5o** [rafaelfranca/simple_form-bootstrap#64]
Hey @rafaelfranca 👋

Of curse, this is a demo application but what do you think setup [depfu](https://depfu.com/) with some clicks to automatically receive dependency and relevant security updates. I volunteer to check the incoming updates.

Heroku would also support automatic deploys, this would be a nice addition. 
* 📝 https://devcenter.heroku.com/articles/github-integration#automatic-deploys

**Comment by rafaelfranca** [comment]
I forgot to setup automatic deploys, just did. I also enabed dependabot.
