### ISSUE TITLE
When trying out this app I get error

### ISSUE THREAD

**Issue by oystersauce8** [rafaelfranca/simple_form-bootstrap#90]
```

ActionView::Template::Error (kramdown has no parser to handle the specified input format: GFM):
    14: 
    15:   <%# move modals to bottom %>
    16:   <%= render partial: "shared/modal", locals: { id: "modal-bootstrap", title: "Bootstrap",
    17:     content: render_source(File.read(File.join(Rails.root, 'app/views/exampleas/verticals/_bootstrap.html.erb'))) } %>
    18: 
    19:   <%= render partial: "shared/modal", locals: { id: "modal-simpleform", title: "Simple Form",
    20:     content: render_source(File.read(File.join(Rails.root, 'app/views/examples/verticals/_form.html.erb'))) } %>
```

**Comment by oystersauce8** [comment]
Also http://simple-form-bootstrap.plataformatec.com.br/examples/vertical
results in

We're sorry, but something went wrong.
If you are the application owner check the logs for more information.

**Comment by m5o** [comment]
Probably because of the upgrade to kramdown `v2.0.0` yesterday 🔗 https://github.com/rafaelfranca/simple_form-bootstrap/pull/89

It seems, the GFM dialect is now a separate parser gem https://github.com/kramdown/parser-gfm
I’ll have a look at this tomorrow, thank you for reporting this issue.
